version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - npm install
      - CI=true npm test
  build:
    commands:
      - npm run build
artifacts:
  base-directory: build
  files:
    - '**/*'